web/router.ex
defmodule BibleStudy.Router do
  use BibleStudy.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BibleStudy do
    pipe_through :browser # Use the default browser stack

    get "/", SearchController, :index
    post "/search", SearchController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", BibleStudy do
  #   pipe_through :api
  # end
end

web/controllers/search_controller.ex
defmodule BibleStudy.SearchController do
  use BibleStudy.Web, :controller
  alias BibleStudy.Bible
  alias BibleStudy.Sermons
  alias BibleStudy.Passage

  def index(conn, _params) do
    conn
    |> assign(:passage, nil)
    |> assign(:scripture, nil)
    |> assign(:sermons, nil)
    |> render("index.html")
  end

  def create(conn, params) do
    passage = get_passage(params)
    conn
    |> assign(:passage, passage.original)
    |> assign(:scripture, get_scripture(passage))
    |> assign(:sermons, get_sermons(passage))
    |> render("index.html")
  end

  defp get_scripture(passage) do
    Bible.find(passage)
  end

  defp get_sermons(passage) do
    Sermons.find(passage)
  end

  defp get_passage(params) do
    %{"passage" => passage} = Map.get(params, "search")
    Passage.new(passage)
  end
end

web/views/search_view.ex
defmodule BibleStudy.SearchView do
  use BibleStudy.Web, :view
end

web/templates/search/index.html.eex
<%= form_for @conn, search_path(@conn, :create), [as: :search, class: "search-form form-inline"], fn f -> %>
  <div class="input-group">
    <%= text_input f, :passage, class: "form-control", placeholder: "e.g. Romans 8:1-5"  %>
    <span class="input-group-btn">
      <button type="submit" value: "Search" class="btn btn-primary">
        <i class="fa fa-search"></i>
      </button>
    </span>
  </div>
<% end %>

<%= if @passage do %>
  <blockquote class="scripture-passage">
    <p class="passage-text"><%= @scripture %></p>
    <footer>
      <cite><%= @passage %> (ESV*)</cite>
    </footer>
  </blockquote>
<% end %>

<div class="sermons-list">
  <%= if @sermons do %>
    <%= for sermon <- @sermons do %>
      <div class="sermon-card">
        <h2 class="sermon-card-header">
          <a href=<%= sermon.url %> target="_blank" class="sermon-title"><%= sermon.title %></a>
        </h2>
        <div class="sermon-card-body">
          <p class="scripture-reference"><%= sermon.scripture_reference %></p>
          <p><%= sermon.date %> by <%= sermon.author %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>


<%= if @passage do %>
  <div class="copyright">
    * The Holy Bible, English Standard Version copyright &copy;&nbsp;2001 by <a target="_blank" href="http://www.crosswaybibles.org">Crossway Bibles</a>, a publishing ministry of Good News Publishers. Used by permission. All rights reserved.
  </div>
<% end %>